### ISSUE TITLE
Will there be a version that runs with iCue5? 

### ISSUE THREAD

**Issue by Cheg5** [ArthurVaiselbuh/HeadsetUtils#4]
Firstly, thank you for this. Being computer illiterate i some how managed to get this working on my system and its exactly what i was looking for. Do you have any plans to make a version for iCue5? The reason i ask is iCue5 is a considerably smaller program size than iCue4.

**Comment by ArthurVaiselbuh** [comment]
Eventually - yes. I currently don't have it installed and don't really have the time to make it work for the new iCue, but I assume it's not too much work. 
I'll probably do it in the next week or two

**Comment by ArthurVaiselbuh** [comment]
So I've been unable to install iCue 5 on my machine due to various errors, and since it's really not that important to me I'm not currently going to make the effort of installing it properly.

However if you provide me with the new log file location on iCue5 and a zip of the new log files I will try making a version that would work on iCue5

**Comment by Cheg5** [comment]
Do you know where I might find the log files, I've looked in the icue 5 folder under program files but nothing stands out as a log file?On 29 Jun 2023 09:22, ArthurVaiselbuh ***@***.***> wrote:
So I've been unable to install iCue 5 on my machine due to various errors, and since it's really not that important to me I'm not currently going to make the effort of installing it properly.
However if you provide me with the new log file location on iCue5 and a zip of the new log files I will try making a version that would work on iCue5

**Comment by ArthurVaiselbuh** [comment]
Try looking under `%LocalAppData%\Corsair`
For example, for iCue4 the location is `C:\Users\[YOUR_USERNAME]\AppData\Local\Corsair\CUE4\logs`

**Comment by Cheg5** [comment]
Thats exactly where it was under CUE5, please find attached the log files.
[logs.zip](https://github.com/ArthurVaiselbuh/HeadsetUtils/files/11946441/logs.zip)

**Comment by ArthurVaiselbuh** [comment]
@Cheg5 The log line for connecting/disconnecting look the same, it's just a matter of changing the log path. 
What's the full path for the log file? Unfortunately you only zipped a couple of the logs.
I assume it's `C:\Users\[USERNAME]\AppData\Local\Corsair\Cue5\logs`, correct?

**Comment by Cheg5** [comment]
Yes that's the correct file path and they're the only logs I have unfortunately as I've been working away.On 4 Jul 2023 17:21, ArthurVaiselbuh ***@***.***> wrote:
@Cheg5 The log line for connecting/disconnecting look the same, it's just a matter of changing the log path.
What's the full path for the log file? Unfortunately you only zipped a couple of the logs.
I assume it's C:\Users\[USERNAME]\AppData\Local\Corsair\Cue5\logs, correct?

**Comment by ArthurVaiselbuh** [comment]
Version [1.0.3](https://github.com/ArthurVaiselbuh/HeadsetUtils/releases/tag/1.0.3) should work with CUE5 or CUE4(latest that's installed).

Let me know if it doesn't.

**Comment by Cheg5** [comment]
It works perfectly, thanks for updating it.
