### ISSUE TITLE
iCUE5 and HeadsetUtils

### ISSUE THREAD

**Issue by NiXTheDev** [ArthurVaiselbuh/HeadsetUtils#6]
### Synopsis
I had not installed the [AudioDeviceCmdlets](https://github.com/frgnca/AudioDeviceCmdlets) in the correct powershell, which led me onto a wild goose chase with regex and then the powershell itself, which in fact i had installed the module, but in the wrong powershell(i.e. the one that wasn't preinstalled(v1) but rather the one that was installed by me(v7))

### What happened

Hello, i am trying to setup HeadsetUtils to work with my iCUE 5(.7.106), and i can't get it to work, i rummaged through the logs and it seems Corsair have again changed how they log (dis/)connection of the devices, and the current version doesn't pick up on that, i have set the config correctly(even to the full names of the devices as reported by the Powershell commandlet, yet no luck

Files:
[iCUE log](https://github.com/ArthurVaiselbuh/HeadsetUtils/files/13063086/2023-10-22_14-35-18.log)
Please pay attention to lines 9, and 43, those're the connect/disconnect events that iCUE logs, that HeadsetUtils doesn't pick up on
HeadsetUtils log doesn't contain anything interesting in either "DEBUG" or "INFO" logging levels, except log spam about checking if event fire is required
![Configuration file](https://github.com/ArthurVaiselbuh/HeadsetUtils/assets/105677206/db2b077d-0daf-4424-b46d-fd0caacb2574)

I should also mention that i have looked through the code of the project and i can see that the regex might be the problem here, it's for iCUE4(?) rather than for iCUE5(I don't actually know, but to me this seems to be the problem

I have also made a mockup for the log regex(which is also available on [Regexr](regexr.com/7m0u3))
```text
^\d{4}\-\d\d\-\d\d\s(?:\d\d\:)*\d\d.\d+\s\w\s(?:\w*\.?){3}\:\s\"(?<Device_Name>\w*)\"\s(?<New_State>\w*)\s->\s(?<Previous_State>\w*)$
```

**Comment by NiXTheDev** [comment]
~~I have set the new regex as the override regex for connect/disconnect but now it fails to run powershell command and exits with code 1, will check why~~
Apparently windows powershell hadn't got the module, will install and re-check

**Comment by NiXTheDev** [comment]
Installed the module, Now everything works

**Comment by pp-arthurvai** [comment]
So happy I could help ;) 

Just kiddibg, glad you could get it to work!

**Comment by NiXTheDev** [comment]
Thanks, though i hope this could be useful to add into the README for example as a "How to setup" section

Edit: Created Pull request to include setup guides for both iCUE4 and iCUE5 in #7 and #10
